### ISSUE TITLE
Collaboration fails

### ISSUE THREAD

**Issue by LordMuetze** [ls1intum/Apollon#319]
### Describe the bug

When trying to share and collaborate on a diagram an error message is displayed:
"Connection to the server failed. Please try again or report a problem."

#### To Reproduce

1. Go to 'Share'
2. Click on 'Collaborate'
4. See error: "Connection to the server failed. Please try again or report a problem."

#### Expected behavior

Get a link or some other possibility to share the diagram for collaboration.

### Environment

<details><pre>
 - OS: Windows 11
 - Browser: Chrome
 - Version: Apollon 2.0.0
</pre></details>

#### Output in Web Console

<details><pre>

;sentry_dsn=https//c3510700e1be402fbe4d773e56406ca8@sentry.ase.in.tum.de/4;/api/diagrams/publish:1 
        
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
main.88a5e89969f864f278f1.js:37 TypeError: Failed to fetch
    at Object.publishDiagramOnServer (main.88a5e89969f864f278f1.js:1:21685)
    at ei.publishDiagram (main.88a5e89969f864f278f1.js:37:29438)
    at ei.<anonymous> (main.88a5e89969f864f278f1.js:37:29135)
    at Ra (vendors.92cc4f912e542f896503.js:772:756232)
    at wl (vendors.92cc4f912e542f896503.js:772:803759)
    at _l (vendors.92cc4f912e542f896503.js:772:803329)
    at vl (vendors.92cc4f912e542f896503.js:772:802867)
    at vendors.92cc4f912e542f896503.js:772:814647
    at xd (vendors.92cc4f912e542f896503.js:772:815158)
    at dd (vendors.92cc4f912e542f896503.js:772:808914)

</pre></details>

**Comment by matthiaslehnertum** [comment]
Hello @LordMuetze , the issue should be resolved now - sorry for your inconvenience!
